"""Improvement proposal store — Metacognition M3.

Manages the self-improvement review queue: prompt/template revision proposals
generated by `maintenance/self_improve.py`, reviewed and approved/rejected via
the `@ling-improve` command. Mirrors the Profiles `_pending` precedent.

The cardinal rule: a proposal is NEVER applied without explicit approval.
Approval is also guarded — it refuses if the target file changed since the
proposal was generated (no clobbering concurrent edits), only writes inside an
allowlist of tunable-asset directories (no path escape into code), and backs
the original up to `_applied/` so every change is one `reject`-style rollback
away.

A proposal is one JSON file in `_pending/<id>.json`:
    {id, created, axis, target_path (vault-relative), rationale,
     addressed_fixes[], original_sha, original_content, revised_content}
"""

from __future__ import annotations

import hashlib
import json
import logging
from datetime import datetime
from pathlib import Path


def _sha(text: str) -> str:
    return hashlib.sha256((text or "").encode("utf-8")).hexdigest()


def make_proposal(
    *, axis: str, target_path: str, rationale: str, addressed_fixes: list,
    original_content: str, revised_content: str, stamp: str | None = None,
) -> dict:
    """Build a proposal dict. `target_path` is relative to the vault root.
    `stamp` lets callers inject a deterministic timestamp (tests)."""
    stamp = stamp or datetime.now().strftime("%Y%m%d%H%M%S")
    pid = f"{Path(target_path).stem}-{stamp}"
    return {
        "id": pid,
        "created": datetime.now().isoformat(timespec="seconds"),
        "axis": axis,
        "target_path": target_path,
        "rationale": rationale,
        "addressed_fixes": list(addressed_fixes or []),
        "original_sha": _sha(original_content),
        "original_content": original_content,
        "revised_content": revised_content,
    }


def save_proposal(proposal: dict, pending_dir: Path) -> Path:
    pending_dir.mkdir(parents=True, exist_ok=True)
    path = pending_dir / f"{proposal['id']}.json"
    path.write_text(json.dumps(proposal, ensure_ascii=False, indent=2), encoding="utf-8")
    return path


def list_proposals(pending_dir: Path) -> list[dict]:
    if not pending_dir.exists():
        return []
    out = []
    for p in sorted(pending_dir.glob("*.json")):
        try:
            out.append(json.loads(p.read_text(encoding="utf-8")))
        except Exception as e:
            logging.warning(f"improvement_store: skipping unreadable {p.name}: {e}")
    return out


def get_proposal(proposal_id: str, pending_dir: Path) -> dict | None:
    path = pending_dir / f"{proposal_id}.json"
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None


def _under_allowlist(target: Path, allowed_dirs: list[Path]) -> bool:
    try:
        target = target.resolve()
    except Exception:
        return False
    for d in allowed_dirs:
        try:
            target.relative_to(d.resolve())
            return True
        except ValueError:
            continue
    return False


def approve_proposal(
    proposal_id: str, *, vault_dir: Path, pending_dir: Path,
    applied_dir: Path, allowed_dirs: list[Path],
) -> dict:
    """Apply a pending proposal. Returns {ok, message, target?}.

    Guards: target must resolve inside `allowed_dirs`; if the live file changed
    since the proposal was generated (sha mismatch), refuse rather than clobber.
    On success the original is backed up under `_applied/<id>.original` and the
    proposal json is moved there too.
    """
    prop = get_proposal(proposal_id, pending_dir)
    if not prop:
        return {"ok": False, "message": f"找不到提案 `{proposal_id}`。"}

    target = vault_dir / prop["target_path"]
    if not _under_allowlist(target, allowed_dirs):
        return {"ok": False, "message": f"目標 `{prop['target_path']}` 不在允許修改的資產目錄內,拒絕套用。"}
    if not target.exists():
        return {"ok": False, "message": f"目標檔不存在：`{prop['target_path']}`。"}

    current = target.read_text(encoding="utf-8")
    if _sha(current) != prop.get("original_sha"):
        return {"ok": False, "message": (
            f"目標 `{prop['target_path']}` 自提案產生後已被改動,拒絕覆蓋（避免蓋掉你的編輯）。"
            f"請重新產生提案。")}

    revised = prop.get("revised_content") or ""
    if not revised.strip():
        return {"ok": False, "message": "提案的修訂內容是空的,拒絕套用。"}

    try:
        applied_dir.mkdir(parents=True, exist_ok=True)
        # Back up the original so approval is one rollback away.
        (applied_dir / f"{proposal_id}.original.md").write_text(current, encoding="utf-8")
        target.write_text(revised, encoding="utf-8")
        (applied_dir / f"{proposal_id}.json").write_text(
            json.dumps({**prop, "applied_at": datetime.now().isoformat(timespec="seconds")},
                       ensure_ascii=False, indent=2), encoding="utf-8")
        (pending_dir / f"{proposal_id}.json").unlink(missing_ok=True)
    except Exception as e:
        return {"ok": False, "message": f"套用時發生錯誤：{e}"}
    return {"ok": True, "message": f"已套用提案 `{proposal_id}` → `{prop['target_path']}`（原檔已備份）。",
            "target": prop["target_path"]}


def reject_proposal(proposal_id: str, *, pending_dir: Path, rejected_dir: Path) -> dict:
    prop = get_proposal(proposal_id, pending_dir)
    if not prop:
        return {"ok": False, "message": f"找不到提案 `{proposal_id}`。"}
    try:
        rejected_dir.mkdir(parents=True, exist_ok=True)
        (rejected_dir / f"{proposal_id}.json").write_text(
            json.dumps({**prop, "rejected_at": datetime.now().isoformat(timespec="seconds")},
                       ensure_ascii=False, indent=2), encoding="utf-8")
        (pending_dir / f"{proposal_id}.json").unlink(missing_ok=True)
    except Exception as e:
        return {"ok": False, "message": f"退回時發生錯誤：{e}"}
    return {"ok": True, "message": f"已退回提案 `{proposal_id}`。"}


def unified_diff(proposal: dict, context: int = 3) -> str:
    """A compact unified diff (original → revised) for human review."""
    import difflib
    orig = (proposal.get("original_content") or "").splitlines()
    new = (proposal.get("revised_content") or "").splitlines()
    diff = difflib.unified_diff(orig, new, fromfile="目前", tofile="提案", n=context, lineterm="")
    return "\n".join(diff)
