import re
import yaml
import logging

def _hybrid_parse(text: str) -> dict:
    """The logic currently in llm_client.py"""
    result = {"title": "Untitled", "tags": [], "type": "entity", "content": text.strip()}
    
    # 1. Find the first YAML block anywhere in the text
    # Current regex: r'---\s*\n(.*?)\n---\s*'
    yaml_match = re.search(r'---\s*\n(.*?)\n---\s*', text, re.DOTALL)
    
    if yaml_match:
        yaml_str = yaml_match.group(1).strip()
        result["content"] = text[yaml_match.end():].strip()
        
        try:
            # Handle markdown symbols at start of line, after brackets, commas, or colons
            yaml_str = re.sub(r'(^|[:\[,\s])[\*\_]{1,2}(.*?)[\*\_]{1,2}(?=[\]\s,:]|$)', r'\1"\2"', yaml_str, flags=re.MULTILINE)
            metadata = yaml.safe_load(yaml_str)
            if isinstance(metadata, dict):
                if "title" in metadata: result["title"] = str(metadata["title"])
                if "tags" in metadata: result["tags"] = metadata["tags"]
                if "type" in metadata: result["type"] = metadata["type"]
        except Exception as e:
            print(f"DEBUG: YAML parse failed: {e}")
            print(f"DEBUG: Offending YAML string:\n{yaml_str}")
    else:
        title_match = re.search(r'^#\s+(.*)', text, re.MULTILINE)
        if title_match:
            result["title"] = title_match.group(1).strip()
            result["content"] = text[title_match.start():].strip()
    
    return result

# --- TEST CASES ---

test_input_1 = """
Here is the analysis of SRP protocol.

---
title: "Secure Remote Password protocol"
tags: ["cryptography", "security"]
type: "entity"
---

# Secure Remote Password (SRP) Protocol
SRP is an augmented password-authenticated key agreement (PAKE) protocol...

---
Disclaimer: This is generated by AI.
"""

print("--- Testing Case 1: Standard with Intro/Outro ---")
res1 = _hybrid_parse(test_input_1)
print(f"Title: {res1['title']}")
print(f"Tags: {res1['tags']}")
print(f"Content Snippet: {res1['content'][:50]}...")

test_input_3 = """
---
**Goal**: "To provide password security"
tags: [**security**, **crypto**]
---
# Content
"""

print("\n--- Testing Case 3: Markdown at line start or inside tags ---")
res3 = _hybrid_parse(test_input_3)
print(f"Goal (if title): {res3['title']}")
print(f"Tags: {res3['tags']}")
